# -*- coding: utf-8 -*-

TWITTER_ACCESS_TOKEN = "234749398-e7VjG5I4VUlCUXlk3kWmN3h4w1IvZziDsOGdyvZn"
TWITTER_ACCESS_TOKEN_SECRET = "TmX5CeMAwTedqGz4xXoH1mJhWeRHY2fALACtVX9aX8"
TWITTER_CONSUMER_KEY = "few1OrMA7uprQmhmY5uDg"
TWITTER_CONSUMER_SECRET = "GUjAT1rTEqiSRkDJaKU7MHUDuUyHTPx1Eod1rAvcQ"

RDIO_API_KEY = ""
RDIO_SHARED_SECRET = ""

IMGUR_CONSUMER_KEY = ''
IMGUR_CONSUMER_SECRET = ''
IMGUR_ACCESS_TOKEN = ''
IMGUR_ACCESS_TOKEN_SECRET = ''
